---
- hosts: localhost

  roles:
    - role: get-vmss-inventory
      vars:
        resource_group_name: "weight-tracker-prod-rg"


- hosts: scalesethosts
  become: true

  roles:
    - role: web-application-setup
      vars:
        env: prod
